---

- name: Ensure apt-transport-https is installed
  apt:
    name: apt-transport-https

- name: Add Nodesource apt key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: Add NodeSource repository
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ nodejs_version }}.x {{ ansible_distribution_release }} main"
    filename: nodesource

- name: Install Node.js
  apt:
    name: nodejs
